apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: typerush_db
  MYSQL_USER: typerush
  MYSQL_PASSWORD: RP738964$
