---
- hosts: webserver
  become: yes

  tasks:

    - name: Stop existing containers
      shell: docker compose down
      args:
        chdir: /home/ubuntu/Team4_Project_Main

    - name: Build Docker image
      shell: docker compose build
      args:
        chdir: /home/ubuntu/Team4_Project_Main

    - name: Start application
      shell: docker compose up -d
      args:
        chdir: /home/ubuntu/Team4_Project_Main